version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cep-application
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    volumes: 
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=cep
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cep.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
