version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cep-application
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes: 
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=cep
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./dataset:/dataset

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./.docker/cache:/data
